CREATE TABLE IF NOT EXISTS json_records
(
	id BIGINT(20) UNSIGNED NOT NULL,
	name VARCHAR(100) NOT NULL UNIQUE,
	value VARCHAR(1024) NOT NULL,
	timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

/* CREATE INDEX idx_json_records_name ON json_records(name) USING BTREE; */
ALTER TABLE json_records ADD INDEX(name) USING BTREE;